[advisories]
vulnerability = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

# Tell cargo-deny to treat 'ahash' as MIT OR Apache-2.0
# without needing to check specific file hashes.
[[licenses.clarify]]
name = "ahash"
expression = "MIT OR Apache-2.0"