[advisories]
vulnerability = "deny"

[licenses]
unlicensed = "deny"
copyleft = "deny"
# Just list the licenses you accept.
# cargo-deny will automatically allow "MIT OR Apache-2.0"
# because both "MIT" and "Apache-2.0" are in this list.
allow = [
    "MIT",
    "Apache-2.0",
]